---
- name: Install PHP & Dependencies
  apt: 
    name: "{{ item }}"
    state: present
  loop:
    - php
    - libapache2-mod-php
    - php-mysql


- name: Extract WordPress
  unarchive:
    src:  "{{ wordpress_url }}"
    dest: "{{ wordpress_path }}"
    remote_src: yes
    creates: "{{ wordpress_path }}*/index.php"


- name: Move files to new location
  copy:
    src: "/var/www/html/wordpress/"
    dest: "/var/www/html/"
    remote_src: yes


- name: Set ownership and permissions for WordPress directory
  file:
    path: "{{ wordpress_path }}"
    state: directory
    owner: www-data 
    group: www-data  
    mode: "0755"

 
- name: Configure WordPress wp-config.php
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wp-config.php

- name: Ensure WordPress config file has correct permissions
  file:
    path: "{{ wordpress_path }}/wp-config.php"
    owner: www-data  
    group: www-data  
    mode: "0644"


- name: Enable WordPress site
  apache2_module:
    state: present
    name: rewrite